version: "3"

services:
  db_mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "robolovo"
      MYSQL_PASSWORD: "robolovo"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./mysql/initdb/init.sql:/docker-entrypoint-initdb.d/1.sql"